const CONCERT_DAY = 0;

const MAX_QUALITY = 50;
const MIN_QUALITY = 0;

const AFTER_CONCERT_DAY = 'AFTER_CONCERT_DAY';
const BEFORE_CONCERT_DAY = 'BEFORE_CONCERT_DAY';
const BEFORE_OR_ON_CONCERT_DAY = 'BEFORE_OR_ON_CONCERT_DAY';

const SELLIN_QUALITY_THRESHOLD_MAP = {
	BACKSTAGE_PASS: {
		5: 3,
		10: 2
	},
	LEGENDARY: {},
	REGULAR: {
		[BEFORE_OR_ON_CONCERT_DAY]: -1,
		[AFTER_CONCERT_DAY]: -2
	},
	CONJURED: {
		[BEFORE_OR_ON_CONCERT_DAY]: -2,
		[AFTER_CONCERT_DAY]: -4
	}
};

module.exports = {
	CONCERT_DAY,
	MAX_QUALITY,
	MIN_QUALITY,
	AFTER_CONCERT_DAY,
	BEFORE_CONCERT_DAY,
	BEFORE_OR_ON_CONCERT_DAY,
	SELLIN_QUALITY_THRESHOLD_MAP
};
